### ISSUE TITLE
如何配置不同的广告商网络呢

### ISSUE THREAD

**Issue by obmutescences** [Risemy/mopub-ad-sdk-android#1]
大哥，怎么配置自定义的广告商网络呢

**Comment by obmutescences** [comment]
可以留个QQ什么的吗，请教交流一下

**Comment by Risemy** [comment]
> 大哥，怎么配置自定义的广告商网络呢

你这边是配置官方支持的第三方广告商还是官方不支持的广告商呢，如果是官方支持的广告商，只需要引用相关网络适配器就可以了，不支持的广告商可以模仿其他广告商的网络适配器，自己写一个自定义网络适配器，官方文档有解释说明的，重写BaseAdapterConfiguration和其他广告类型，如激励视频重写CustomEventRewardedVideo

**Comment by obmutescences** [comment]
> > 大哥，怎么配置自定义的广告商网络呢
> 
> 你这边是配置官方支持的第三方广告商还是官方不支持的广告商呢，如果是官方支持的广告商，只需要引用相关网络适配器就可以了，不支持的广告商可以模仿其他广告商的网络适配器，自己写一个自定义网络适配器，官方文档有解释说明的，重写BaseAdapterConfiguration和其他广告类型，如激励视频重写CustomEventRewardedVideo

好的，谢谢哈
